### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by chenjun2hao** [lvpengyuan/masktextspotter.caffe2#17]
when test the infer.py with ICDAR2015 dataset, it print out the problem:
```python
Traceback (most recent call last):
  File "tools/test_net.py", line 169, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing, vis=vis)
  File "tools/test_net.py", line 139, in main
    parent_func(multi_gpu=multi_gpu_testing, vis=vis)
  File "./lib/core/test_engine.py", line 64, in test_net_on_dataset
    test_net(vis=vis)
  File "./lib/core/test_engine.py", line 150, in test_net
    model, im, image_name, box_proposals, timers, vis=vis
  File "./lib/core/test.py", line 150, in im_detect_all
    text, rec_score, rec_char_scores = getstr_grid(char_masks[index,:,:,:].copy(), box_w, box_h)
  File "./lib/core/test.py", line 1107, in getstr_grid
    string, score, rec_scores = seg2text(pos, mask_index, seg)
  File "./lib/core/test.py", line 1216, in seg2text
    im2, contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
```

**Comment by tianzhuotao** [comment]
contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
