### ISSUE TITLE
ValueError: Type mismatch (<type 'tuple'> vs. <type 'str'>) with values (() vs. icdar2015_test) for config key: TEST.DATASETS

### ISSUE THREAD

**Issue by luckyXZR** [lvpengyuan/masktextspotter.caffe2#22]
I try python tools/test_net.py --cfg configs/text/mask_textspotter.yaml
but i can not import datasets

the problem is as follows: 
make: Entering directory '/home/xie/MaskTextSpotter/lanms'
make: 'adaptor.so' is up to date.
make: Leaving directory '/home/xie/MaskTextSpotter/lanms'
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO test_net.py: 142: Called with args:
INFO test_net.py: 143: Namespace(cfg_file='configs/text/mask_textspotter.yaml', multi_gpu_testing=False, opts=[], range=None, vis=False, wait=True)
Traceback (most recent call last):
  File "tools/test_net.py", line 145, in <module>
    merge_cfg_from_file(args.cfg_file)
  File "/home/MaskTextSpotter/lib/core/config.py", line 1095, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/home/MaskTextSpotter/lib/core/config.py", line 1153, in _merge_a_into_b
    _merge_a_into_b(v, b[k], stack=stack_push)
  File "/home/MaskTextSpotter/lib/core/config.py", line 1147, in _merge_a_into_b
    v = _check_and_coerce_cfg_value_type(v, b[k], k, full_key)
  File "/home/MaskTextSpotter/lib/core/config.py", line 1242, in _check_and_coerce_cfg_value_type
    'key: {}'.format(type_b, type_a, value_b, value_a, full_key)
ValueError: Type mismatch (<type 'tuple'> vs. <type 'str'>) with values (() vs. icdar2015_test) for config key: TEST.DATASETS

**Comment by ldfinfontainebleau** [comment]
It seems value of TEST.DATASETS in mask_textspotter.yaml is not correct.
