### ISSUE TITLE
workspace.RunNet(model.net.Proto().name)

### ISSUE THREAD

**Issue by Serissa** [lvpengyuan/masktextspotter.caffe2#34]
请问谁有遇到，程序执行到workspace.RunNet(model.net.Proto().name)就返回了，请问怎么解决？

**Comment by zhoujianwen** [comment]
```
.................................
INFO optimizer.py: 103: param gpu_0/mask_fcn_char_logits_b will be updated
WARNING memonger.py:  55: NOTE: Executing memonger to optimize gradient memory
[I memonger.cc:236] Remapping 95 using 23 shared blobs.
INFO memonger.py:  97: Memonger memory optimization took 0.00892996788025 secs
Traceback (most recent call last):
  File "tools/train_net.py", line 372, in <module>
    main()
  File "tools/train_net.py", line 198, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 221, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/home/zhoujianwen/anaconda2/envs/caffe2_env/lib/python2.7/site-packages/caffe2/python/workspace.py", line 245, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/zhoujianwen/anaconda2/envs/caffe2_env/lib/python2.7/site-packages/caffe2/python/workspace.py", line 206, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1136] gWorkspace->GetNet(name). Can't find net generalized_rcnn
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x76 (0x7f13b1c1a7b6 in /home/zhoujianwen/anaconda2/envs/caffe2_env/lib/libc10.so)
frame #1: <unknown function> + 0x46bee (0x7f13dda9bbee in /home/zhoujianwen/anaconda2/envs/caffe2_env/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #2: <unknown function> + 0x93250 (0x7f13ddae8250 in /home/zhoujianwen/anaconda2/envs/caffe2_env/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
<omitting python frames>
frame #18: __libc_start_main + 0xf0 (0x7f13e0cae830 in /lib/x86_64-linux-gnu/libc.so.6)
.....................................
```

RuntimeError: [enforce fail at pybind_state.cc:1136] gWorkspace->GetNet(name). Can't find net generalized_rcnn

**Comment by zhoujianwen** [comment]
@lvpengyuan Can't train the model,keep reporting errors,I don't know why?But I can train detectron's model.

**Comment by zhoujianwen** [comment]
@Serissa Have you solved your problem?
 gWorkspace->GetNet(name). Can't find net generalized_rcnn
# Execute the training run
    checkpoints = train_model()

My code runs here with an error because the return value is NULL.
