### ISSUE TITLE
cannot import name test_retinanet

### ISSUE THREAD

**Issue by LousyLory** [lvpengyuan/masktextspotter.caffe2#45]
Traceback (most recent call last):
File "tools/test_net.py", line 42, in 
from core.test_retinanet import test_retinanet
ImportError: cannot import name test_retinanet

**Comment by brooklyn1900** [comment]
same question! I can't find the test_retinanet function in the test_retinanet.py

**Comment by brooklyn1900** [comment]
> Hi @lvpengyuan,
> 
> I am getting the following error while running `python tools/test_net.py --cfg configs/text/mask_textspotter.yaml`
> Traceback (most recent call last):
> File "tools/test_net.py", line 42, in
> from core.test_retinanet import test_retinanet
> ImportError: cannot import name test_retinanet

Solved this. It's in masktextspotter.caffe2/lib/core/test_retinanet
