### ISSUE TITLE
AttributeError: Method AffineChannel is not a registered operator.

### ISSUE THREAD

**Issue by Shualite** [lvpengyuan/masktextspotter.caffe2#50]
`WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
Traceback (most recent call last):
  File "tools/test_net.py", line 157, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing, vis=vis)
  File "tools/test_net.py", line 127, in main
    parent_func(multi_gpu=multi_gpu_testing, vis=vis)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/core/test_engine.py", line 64, in test_net_on_dataset
    test_net(vis=vis)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/core/test_engine.py", line 126, in test_net
    model = initialize_model_from_cfg()
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/core/test_engine.py", line 158, in initialize_model_from_cfg
    model = model_builder.create(cfg.MODEL.TYPE, train=False)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/model_builder.py", line 119, in create
    return get_func(model_type_func)(model)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/model_builder.py", line 91, in generalized_rcnn
    freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/model_builder.py", line 224, in build_generic_detection_model
    optim.build_data_parallel_model(model, _single_gpu_build_func)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/optimizer.py", line 51, in build_data_parallel_model
    single_gpu_build_func(model)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/model_builder.py", line 164, in _single_gpu_build_func
    blob_conv, dim_conv, spatial_scale_conv = add_conv_body_func(model)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/FPN.py", line 47, in add_fpn_ResNet50_conv5_body
    model, ResNet.add_ResNet50_conv5_body, fpn_level_info_ResNet50_conv5
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/FPN.py", line 103, in add_fpn_onto_conv_body
    conv_body_func(model)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/ResNet.py", line 39, in add_ResNet50_conv5_body
    return add_ResNet_convX_body(model, (3, 4, 6, 3), use_deformable=use_deformable)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/ResNet.py", line 98, in add_ResNet_convX_body
    p = model.AffineChannel(p, 'res_conv1_bn', inplace=True)
  File "/root/fsy_SceneTextRec/masktextspotter.caffe2-master/lib/modeling/detector.py", line 104, in AffineChannel
    return self.net.AffineChannel([blob_in, scale, bias], blob_in)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/core.py", line 2040, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method AffineChannel is not a registered operator. Did you mean: []`

I wonder whether this problem results from the Detectron package error installation. By the way, when i install the detectron package follow a dockerfile inside, no problems were shown.

**Comment by Shualite** [comment]
@lvpengyuan
